# Generated by Django 3.2 on 2023-02-06 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Level',
            },
        ),
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_type',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('regNo', models.CharField(max_length=14, unique=True)),
                ('NTA_Level', models.CharField(blank=True, max_length=2, null=True)),
                ('academic_year', models.CharField(max_length=12)),
                ('mobile', models.CharField(blank=True, max_length=14, null=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pic')),
                ('course', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('staff_id', models.IntegerField(unique=True)),
                ('mobile', models.TextField(blank=True, max_length=14, null=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pic/staff')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.department')),
                ('level', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.department')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.project_type')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.student')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=10)),
                ('comments', models.TextField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.document')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.staff')),
            ],
            options={
                'db_table': 'progress',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.project'),
        ),
    ]
