# Generated by Django 3.2 on 2023-04-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20230324_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='staff',
        ),
    ]
