# Generated by Django 3.2 on 2023-02-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_type',
            name='dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.department'),
        ),
    ]
