# Generated by Django 3.2 on 2023-02-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_project_type_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
