# Generated by Django 3.2 on 2023-05-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20230425_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='prog',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
