# Generated by Django 3.2 on 2023-02-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
