# Generated by Django 3.2 on 2023-05-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_auto_20230503_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='academic_year',
            field=models.CharField(blank=True, default='2022/2023', max_length=50, null=True),
        ),
    ]
