# Generated by Django 3.2 on 2023-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_submission_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
