# Generated by Django 3.2 on 2023-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_remove_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='comments',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='NTA_Level',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
