# Generated by Django 3.2 on 2023-02-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_auto_20230212_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_type',
            old_name='dept_id',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='NTA_Level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
