# Generated by Django 3.2 on 2023-05-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='preview'),
        ),
    ]
