# Generated by Django 3.2 on 2023-05-31 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_document_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.level')),
            ],
            options={
                'db_table': 'Awards',
            },
        ),
    ]
