# Generated by Django 3.2 on 2023-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_auto_20230213_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_type',
            name='department',
        ),
        migrations.AddField(
            model_name='project_type',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='archives.Department'),
        ),
    ]
