# Generated by Django 3.2 on 2023-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0008_auto_20230213_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_type',
            name='department',
            field=models.ManyToManyField(to='archives.Department'),
        ),
    ]
