# Generated by Django 3.2 on 2023-06-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0008_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.level'),
        ),
    ]
