# Generated by Django 3.2 on 2023-06-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_alter_staff_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='departmenet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.department'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.level'),
        ),
    ]
