# Generated by Django 3.2 on 2023-02-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_alter_project_type_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_type',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='project_type',
            field=models.ManyToManyField(to='archives.Project_type'),
        ),
    ]
