# Generated by Django 3.2 on 2023-06-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_auto_20230611_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='departmenet',
            new_name='department',
        ),
    ]
