# Generated by Django 3.2 on 2023-02-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_auto_20230213_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project_type',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.department'),
        ),
    ]
