# Generated by Django 3.2 on 2023-02-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0016_auto_20230221_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.document'),
        ),
    ]
