# Generated by Django 3.2 on 2023-02-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0019_remove_progress_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
