# Generated by Django 3.2 on 2023-02-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0020_progress_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='progress',
            new_name='prog',
        ),
    ]
