# Generated by Django 3.2 on 2023-02-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0023_auto_20230221_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.project'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='prog',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
