# Generated by Django 3.2 on 2023-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0024_auto_20230225_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cover',
        ),
        migrations.AddField(
            model_name='document',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
    ]
