# Generated by Django 3.2 on 2023-03-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0027_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'default_permissions': '', 'permissions': (('like_document', 'Can like documents'), ('can_hire', 'Can hire employees'))},
        ),
    ]
