# Generated by Django 3.2 on 2023-03-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0029_alter_likes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={},
        ),
        migrations.AlterModelTable(
            name='likes',
            table='Likes',
        ),
        migrations.AlterModelTable(
            name='submission',
            table='submission',
        ),
    ]
