# Generated by Django 3.2 on 2023-03-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0031_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
