# Generated by Django 3.2 on 2023-03-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0032_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
